name: Dependency updated

on:
  push:
    branches:
      - main

jobs:
  trigger-external-pr:
    runs-on: ubuntu-latest
    env:
        REPOSITORY_PATH: 'pavelmaksimov25/auto_merge_test_main'
        PHP_VERSION: '8.2'
    steps:
      - name: Echo env vars
        run: echo "Repository path is " $REPOSITORY_PATH

      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: $PHP_VERSION
            tools: composer:v2

      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
            github-token: ${{ secrets.PAT }}
            sha: ${{ github.event.pull_request.head.sha }}

      - name: Get PR details
        run: echo "The PR number is ${prNumber}"
        if: success() && steps.PR.outputs.number
        env:
          prNumber: ${{ steps.PR.outputs.number }}

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: $REPOSITORY_PATH
          path: main
          fetch-depth: 0

      - name: Update composer
        run: |
          composer update
          composer install
          composer dump-autoload
        working-directory: main

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          path: main
          branch: $REPOSITORY_PATH/${{ env.prBranchName }}
          delete-branch: true
          title: ${{ format('Dependency update. {0}', env.prTitle) }}
          body: ${{ format('{0} Dependency PR [{1}]({2}).', env.prBody, env.prNumber, env.prUrl) }}
          labels: dependencies
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBranchName: ${{ fromJson(steps.PR.outputs.pr).head.ref }}
          prBody: ${{ steps.PR.outputs.pr_body }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
