name: Dependency updated

on:
  push:
    branches:
      - main

jobs:
  trigger-external-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.2'
            tools: composer:v2

      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
            github-token: ${{ secrets.PAT }}
            sha: ${{ github.event.pull_request.head.sha }}

      - name: Get PR details
        run: echo "The PR number is ${prNumber}"
        if: success() && steps.PR.outputs.number
        env:
          prNumber: ${{ steps.PR.outputs.number }}

      - name: "Checkout target repository"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: pavelmaksimov25/auto_merge_test_main
          path: main
          fetch-depth: 0

      - name: "Update composer"
        run: |
          composer update
          composer install
          composer dump-autoload
        working-directory: main

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        working-directory: main
        env:
            prNumber: ${{ steps.PR.outputs.number }}
            prBranchName: ${{ fromJson(steps.PR.outputs.pr).head.ref }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          path: main
          branch: pavelmaksimov25/auto_merge_test_main/${{ env.prBranchName }}
          delete-branch: true
          title: ${{ steps.PR.outputs.title }}
          body: ${{ steps.PR.outputs.pr_body }}
          labels: dependencies
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prBranchName: ${{ fromJson(steps.PR.outputs.pr).head.ref }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
