name: Dependency updated

on:
  push:
    branches:
      - main

jobs:
  trigger-external-pr:
    runs-on: ubuntu-latest
    env:
        OWNER: 'pavelmaksimov25'
        REPO: 'auto_merge_test_main'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.2
            tools: composer:v2

      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
            github-token: ${{ secrets.PAT }}
            sha: ${{ github.event.pull_request.head.sha }}

      - name: "Get PR details"
        run: echo "The PR number is ${prNumber}"
        if: success() && steps.PR.outputs.number
        env:
          prNumber: ${{ steps.PR.outputs.number }}

      - name: "Checkout target repository"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.OWNER }}/${{ env.REPO }}
          path: main
          fetch-depth: 0

      - name: "Update composer"
        run: |
          composer update pavelmaksimov25/auto_merge_test_dep -n
          echo 'test additional file' >> README.md
        working-directory: main

      - name: "Prepare PR Body"
        if: ${{ success() }}
        id: target-pr-body
        run: |
            target_pr_body="This PR is automatically created by GitHub action to update dependency.
            Original PR [${{ steps.PR.outputs.number }}](${{ steps.PR.outputs.pr_url }})
            Original PR Body:
            ${{ steps.PR.outputs.pr_body }}"

            echo 'target_pr_body<<EOF' >> $GITHUB_OUTPUT
            echo "$target_pr_body" >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT

      - name: "Create Pull Request"
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          path: main
          branch: ${{ format('{0}-dependency-{1}-{2}', env.prBranchName, env.sourceProject, env.prNumber) }}
          delete-branch: true
          title: ${{ format('Dependency update. {0}', env.prTitle) }}
          body: ${{ env.prBody }}
          labels: dependencies
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBranchName: ${{ fromJson(steps.PR.outputs.pr).head.ref }}
          prBody: ${{ steps.target-pr-body.outputs.target_pr_body }}
          sourceProject: ${{ env.REPO }}
